from __future__ import annotations

import argparse
import wave
from pathlib import Path

import librosa
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate librosa.effects.split reference intervals for a WAV file."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("../RECITATION324_158.wav"),
        help="Input WAV path.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("../tests/data/RECITATION324_158.librosa_split.txt"),
        help="Output interval text file.",
    )
    parser.add_argument("--top-db", type=float, default=60.0)
    parser.add_argument("--frame-length", type=int, default=2048)
    parser.add_argument("--hop-length", type=int, default=512)
    return parser.parse_args()


def load_pcm16_mono_wav(path: Path) -> tuple[np.ndarray, int]:
    with wave.open(str(path), "rb") as wav_file:
        if wav_file.getcomptype() != "NONE":
            raise ValueError(f"{path} is not an uncompressed PCM WAV file")
        if wav_file.getnchannels() != 1:
            raise ValueError(f"{path} must be mono")
        if wav_file.getsampwidth() != 2:
            raise ValueError(f"{path} must use 16-bit PCM samples")

        sample_rate_hz = wav_file.getframerate()
        pcm = np.frombuffer(wav_file.readframes(wav_file.getnframes()), dtype="<i2")

    audio = pcm.astype(np.float32) / 32768.0
    return audio, sample_rate_hz


def write_intervals(
    output_path: Path,
    input_path: Path,
    sample_rate_hz: int,
    top_db: float,
    frame_length: int,
    hop_length: int,
    intervals: np.ndarray,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as output:
        output.write("# Generated by test_data_gen/generate_librosa_vad_reference.py\n")
        output.write(f"# source={input_path.name}\n")
        output.write(f"# sample_rate_hz={sample_rate_hz}\n")
        output.write(f"# librosa_version={librosa.__version__}\n")
        output.write(f"# top_db={top_db}\n")
        output.write(f"# frame_length={frame_length}\n")
        output.write(f"# hop_length={hop_length}\n")
        for begin, end in intervals.tolist():
            output.write(f"{begin} {end}\n")


def main() -> None:
    args = parse_args()
    audio, sample_rate_hz = load_pcm16_mono_wav(args.input)
    intervals = librosa.effects.split(
        audio,
        top_db=args.top_db,
        ref=np.max,
        frame_length=args.frame_length,
        hop_length=args.hop_length,
    )
    write_intervals(
        output_path=args.output,
        input_path=args.input,
        sample_rate_hz=sample_rate_hz,
        top_db=args.top_db,
        frame_length=args.frame_length,
        hop_length=args.hop_length,
        intervals=intervals,
    )
    print(f"Wrote {len(intervals)} intervals to {args.output}")


if __name__ == "__main__":
    main()
